Add GitHub Actions CI
LumaTeam/Luma3DS pull request #1389
Opened 2020-04-03 00:21 UTC by Margen67

Heavily based off of https://github.com/hax0kartik/luma-hourlies by @hax0kartik.

2020-04-15 20:42 UTC, TuxSH requested changes
In general, why reinstall everything at every CI trigger? Is it not possible to use a docker image with everything set up instead?

2020-04-15 20:42 UTC, TuxSH commented on .github/workflows/CI.yml
> +        git clone --depth=1 https://github.com/smealum/ctrulib.git && \
I don't think this is needed, is it? Will check if docker image is up to date?

2020-04-15 21:40 UTC, Margen67 commented
> 
> 
> In general, why reinstall everything at every CI trigger? Is it not possible to use a docker image with everything set up instead?

As far as I know that would require making a Dockerfile/image.

2020-04-15 21:50 UTC, TuxSH commented on .github/workflows/CI.yml
> +        git clone --depth=1 https://github.com/smealum/ctrulib.git && \
nevermind, relies on acu

2020-04-24 03:46 UTC, Margen67 commented on .github/workflows/CI.yml
> +        git clone --depth=1 https://github.com/smealum/ctrulib.git && \
I tried a Luma3DS Docker image, but it fails:
https://hub.docker.com/r/nanquitas/luma3ds
https://github.com/Margen67/Luma3DS/runs/599002429

If the Docker images were up-to-date that would make things easier: https://github.com/devkitPro/docker/issues/6

2020-06-01 19:07 UTC, Margen67 commented
Thanks to @Nanquitas updating their Docker image this can be done cleanly now.
@jbmagination you might want to use this improved version.

2020-06-02 00:23 UTC, jbmagination commented
@TuxSH?

Also yes, I will use that version.

2020-09-06 11:15 UTC, closed without merging