Patched svcCreateThread() for core 2 and 3 on new 3DS
LumaTeam/Luma3DS pull request #1668
Opened 2021-08-24 07:07 UTC by Core-2-Extreme

Patch native.firm to always be able to create thread on core 2 and 3 from user app.
I just patched `if(processorid == 0x2) to if(processorid == 0x4)` and `if(processorid == 0x3) to if(processorid == 0x4)` so it won't return 0xD9001BEA.

I tested it and worked on new 3DS firm version 11.15.0.47J, 11.15.0.47U and 11.14.0.46J.

2022-01-06 14:40 UTC, Frenzoid approved these changes

2022-09-25 11:03 UTC, PabloMK7 commented
The patches made to kernel11 are hardcoded, so it will only ever work with a single firmware version (which you don't specify btw :P) The way to fix this would be to use pattern search like all the other patches.

2022-11-10 12:48 UTC, Core-2-Extreme commented
I updated to pattern search.

2022-11-14 13:05 UTC, PabloMK7 commented on arm9/source/patches.c
> +    static const u8 pattern[] = { 0x02, 0x00, 0x59, 0xE3, 0x0C, 0x00, 0x00, 0x0A, };
```suggestion
    static const u8 pattern[] = { 0x02, 0x00, 0x59, 0xE3, 0x0C, 0x00, 0x00, 0x0A };
```

2022-11-14 13:05 UTC, PabloMK7 commented on arm9/source/patches.c
> +    offset[1] = __builtin_bswap32(0x040059E3);
```suggestion
    offset[1] = 0xE3590004
```

2022-11-14 13:05 UTC, PabloMK7 commented on arm9/source/patches.c
> +    static const u8 pattern[] = { 0x03, 0x00, 0x59, 0xE3, 0x0D, 0x00, 0x00, 0x0A, };
```suggestion
    static const u8 pattern[] = { 0x03, 0x00, 0x59, 0xE3, 0x0D, 0x00, 0x00, 0x0A };
```

2022-11-14 13:06 UTC, PabloMK7 commented on arm9/source/patches.c
> +    offset[1] = __builtin_bswap32(0x040059E3);
```suggestion
    offset[1] = 0xE3590004
```

2022-11-14 13:08 UTC, PabloMK7 requested changes
Check suggested changes.

2022-11-15 12:00 UTC, Core-2-Extreme commented
I'm not sure, and I don't have old `native.firm` so I couldn't check it.

2022-11-15 16:32 UTC, PabloMK7 commented
You didn't apply the suggestions, but marked them as resolved, was that intended? lol

2022-11-16 10:38 UTC, Core-2-Extreme commented
No, I thought if I press the resolve button, it'll be merged in my code.
I think I applied your suggestions now, if it is wrong, let me know.

2022-11-17 23:01 UTC, TuxSH commented
Is there a use case for the core2 patch?

Core2 access is granted via a kernel capability, which we automatically grant to all 3dsx apps.

2022-11-17 23:38 UTC, PabloMK7 commented
> Is there a use case for the core2 patch?

For the same reason as svc and service pathes, I guess :P. [Also 3GX plugins](https://gitlab.com/thepixellizeross/ctrpluginframework/-/blob/f7aed655468af724ab78bb347bf5ece7369a3ccc/Library/source/ctrulibExtension/thread.c#L81-83).

2022-11-18 11:44 UTC, Core-2-Extreme commented
> Is there a use case for the core2 patch?

Does luma3ds grant access to core 2 even if kernel-flags bitmask 0x2000 is not set?
> When processorid==0x2 and the process is not a BASE mem-region process, exheader kernel-flags bitmask 0x2000 must be set (otherwise error 0xD9001BEA is returned).
(https://www.3dbrew.org/wiki/Multi-threading)

I was thinking that if homebrew launcher (any app that starts `.3dsx` app) doesn't have it then `.3dsx` app can't get access to core 2 results in some app not being worked in `.3dsx` while it works in `.cia`.

2022-11-18 13:49 UTC, TuxSH commented
> Does luma3ds grant access to core 2 even if kernel-flags bitmask 0x2000 is not set?

Yes, it sets it when creating a process.

The homebrew launcher app's exheader or code is never actually used, Luma3DS hijacks the loading of the target program (you can set homebrew loader titleId to match the Download Play app, for example).

2022-11-19 03:28 UTC, Core-2-Extreme commented
> Yes, it sets it when creating a process.

ok, then core2 patch is not necessary, but should I remove it?
(I think it won't hurt anything)

2022-11-19 03:57 UTC, PabloMK7 commented
I see this as a positive addition, I don't think it hurts having it.

2022-12-17 22:53 UTC, closed without merging

2022-12-17 22:55 UTC, TuxSH commented
Sorry if I took a long time to deal with this. I ended up writing the patch differently.

For what it's worth https://github.com/devkitPro/3ds-examples/blob/master/threads/thread-basic/source/main.c modified to use core 3 for all spawned threads often resulted in one or multiple threads being starved.

2023-01-05 06:49 UTC, Core-2-Extreme commented
> For what it's worth https://github.com/devkitPro/3ds-examples/blob/master/threads/thread-basic/source/main.c modified to use core 3 for all spawned threads often resulted in one or multiple threads being starved in my tests.

Did you fix this problem in your new patch?
If not, is there different between my patch?

2023-01-07 15:42 UTC, TuxSH commented
No, please read the commit message. This is not something you can fix, QTM is running at very high priority on core3, and the GPU driver depends on QTM on N3DS.