Add more mountpoint names for LayeredFS updates
LumaTeam/Luma3DS pull request #1994
Opened 2024-02-01 21:11 UTC by CyberYoshi64

Mario Kart 7 uses the mountpoint name `pat1` for its update.
SmileBASIC 3 (and probably other SmileBoom titles that got updates) use `ro2:`

This is in reference to my issue #1993.
I haven't really got the drill of PR's just yet but I hope it works.

2024-02-01 21:58 UTC, PabloMK7 commented
Have you verified `pat1` is the update for MK7? Also, could you place it last as I hav ethe feeling it could cause false positives due to missing semicolon.

2024-02-01 22:12 UTC, CyberYoshi64 commented
> Have you verified `pat1` is the update for MK7 (by trying to replace files)? Also, could you place it last as I have the feeling it could cause false positives due to missing semicolon.

Yes, I have tested it, by replacing in-game strings, as well as the online icon. It only works without the colon, which is unusual and rather outstanding, I agree.

2024-02-01 23:08 UTC, PabloMK7 commented
Sorry, when I meant move to the bottom I meant above `rom:`. In any case, I think it may be worth checking for the mk7 TID specifically to prevent false positives.

2024-02-02 10:01 UTC, PabloMK7 requested changes
Removed casts to char* and reduced the size of the TIDs to save space

2024-02-02 10:01 UTC, PabloMK7 commented on sysmodules/loader/source/patcher.c
> +    char *updateRomFsMount;
```suggestion
    const char *updateRomFsMount;
```

2024-02-02 10:01 UTC, PabloMK7 commented on sysmodules/loader/source/patcher.c
> +        updateRomFsMount = (char*)updateRomFsMounts[updateRomFsIndex];
```suggestion
        updateRomFsMount = updateRomFsMounts[updateRomFsIndex];
```

2024-02-02 10:01 UTC, PabloMK7 commented on sysmodules/loader/source/patcher.c
> +        updateRomFsMount = (char*)"pat1"; // Isolated to prevent false-positives
```suggestion
        updateRomFsMount = "pat1"; // Isolated to prevent false-positives
```

2024-02-02 10:01 UTC, PabloMK7 commented on sysmodules/loader/source/patcher.c
> +                        progId == 0x000400000008B400LL;   //TWN MK7
```suggestion
    bool isMarioKart7 = (u32)progId == 0x00030600 || //JPN MK7
                        (u32)progId == 0x00030700 || //EUR MK7
                        (u32)progId == 0x00030800 || //USA MK7
                        (u32)progId == 0x00030A00 || //KOR MK7
                        (u32)progId == 0x0008B400;   //TWN MK7
```

2024-02-02 13:41 UTC, PabloMK7 approved these changes

2024-02-02 13:42 UTC, merged